### PR TITLE
Update the date picker module to fix IE issues

### PR DESCRIPTION
**Pull request by cameronviner**
#### What does this PR do? (please provide any background)

There is an issue with the module we were using for the datpicker that caused the calendar to flash constantly in IE browsers, I have update the module we point at in order to get there fix for the problem.

#### What tests does this PR have?

None, existing tests should cover the changes

#### How can this be tested?

npm install and then run npm start and make sure the calendars behave correctly in IE.

#### What gif best describes how you feel about this work?

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2**
- [x] :+1:

**Review 3**
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

### CODE REVIEW

**Comment by GeorgeF72** [comment]
1️⃣

**Comment by samsmarthx** [comment]
Taking✌️

**Comment by hx-markterry** [comment]
looks good to me 👐

**Comment by GeorgeF72** [comment]
All fixed in IE 👍

**Comment by samsmarthx** [comment]
Looks good! 👍

**Pull request merged**
